// src/constants.tsx

export const DEFAULT_MAX_CHAR_LIMIT = 6000;

export const LANGUAGE_CODE_MAP = {
  "it": "Italian",
  "de": "German",
  "fr": "French",
  "es": "Spanish",
  "en": "English",
  "ab": "Abkhazian",
  "aa": "Afar",
  "af": "Afrikaans",
  "ak": "Akan",
  "sq": "Albanian",
  "am": "Amharic",
  "ar": "Arabic",
  "an": "Aragonese",
  "hy": "Armenian",
  "as": "Assamese",
  "av": "Avaric",
  "ae": "Avestan",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "bm": "Bambara",
  "ba": "Bashkir",
  "eu": "Basque",
  "be": "Belarusian",
  "bn": "Bengali",
  "bi": "Bislama",
  "bs": "Bosnian",
  "br": "Breton",
  "bg": "Bulgarian",
  "my": "Burmese",
  "ca": "Catalan",
  "ch": "Chamorro",
  "ce": "Chechen",
  "ny": "Chichewa",
  "zh": "Chinese",
  "cu": "Church Slavonic",
  "cv": "Chuvash",
  "kw": "Cornish",
  "co": "Corsican",
  "cr": "Cree",
  "hr": "Croatian",
  "cs": "Czech",
  "da": "Danish",
  "dv": "Divehi",
  "nl": "Dutch",
  "dz": "Dzongkha",
  "eo": "Esperanto",
  "et": "Estonian",
  "ee": "Ewe",
  "fo": "Faroese",
  "fj": "Fijian",
  "fi": "Finnish",
  "fy": "Western Frisian",
  "ff": "Fulah",
  "gd": "Gaelic",
  "gl": "Galician",
  "lg": "Ganda",
  "ka": "Georgian",
  "el": "Greek",
  "kl": "Kalaallisut",
  "gn": "Guarani",
  "gu": "Gujarati",
  "ht": "Haitian",
  "ha": "Hausa",
  "he": "Hebrew",
  "hz": "Herero",
  "hi": "Hindi",
  "ho": "Hiri Motu",
  "hu": "Hungarian",
  "is": "Icelandic",
  "io": "Ido",
  "ig": "Igbo",
  "id": "Indonesian",
  "ia": "Interlingua (International Auxiliary Language Association)",
  "ie": "Interlingue, Occidental",
  "iu": "Inuktitut",
  "ik": "Inupiaq",
  "ga": "Irish",
  "ja": "Japanese",
  "jv": "Javanese",
  "kn": "Kannada",
  "kr": "Kanuri",
  "ks": "Kashmiri",
  "kk": "Kazakh",
  "km": "Central Khmer",
  "ki": "Kikuyu",
  "rw": "Kinyarwanda",
  "ky": "Kyrgyz",
  "kv": "Komi",
  "kg": "Kongo",
  "ko": "Korean",
  "kj": "Kuanyama",
  "ku": "Kurdish",
  "lo": "Lao",
  "la": "Latin",
  "lv": "Latvian",
  "li": "Limburgan",
  "ln": "Lingala",
  "lt": "Lithuanian",
  "lu": "Luba-Katanga",
  "lb": "Luxembourgish",
  "mk": "Macedonian",
  "mg": "Malagasy",
  "ms": "Malay",
  "ml": "Malayalam",
  "mt": "Maltese",
  "gv": "Manx",
  "mi": "Maori",
  "mr": "Marathi",
  "mh": "Marshallese",
  "mn": "Mongolian",
  "na": "Nauru",
  "nv": "Navajo, Navaho",
  "nd": "North Ndebele",
  "nr": "South Ndebele",
  "ng": "Ndonga",
  "ne": "Nepali",
  "no": "Norwegian",
  "nb": "Norwegian Bokmål",
  "nn": "Norwegian Nynorsk",
  "oc": "Occitan",
  "oj": "Ojibwa",
  "or": "Oriya",
  "om": "Oromo",
  "os": "Ossetian",
  "pi": "Pali",
  "ps": "Pashto, Pushto",
  "fa": "Persian",
  "pl": "Polish",
  "pt": "Portuguese",
  "pa": "Punjabi",
  "qu": "Quechua",
  "ro": "Romanian",
  "rm": "Romansh",
  "rn": "Rundi",
  "ru": "Russian",
  "se": "Northern Sami",
  "sm": "Samoan",
  "sg": "Sango",
  "sa": "Sanskrit",
  "sc": "Sardinian",
  "sr": "Serbian",
  "sn": "Shona",
  "sd": "Sindhi",
  "si": "Sinhala",
  "sk": "Slovak",
  "sl": "Slovenian",
  "so": "Somali",
  "st": "Southern Sotho",
  "su": "Sundanese",
  "sw": "Swahili",
  "ss": "Swati",
  "sv": "Swedish",
  "tl": "Tagalog",
  "ty": "Tahitian",
  "tg": "Tajik",
  "ta": "Tamil",
  "tt": "Tatar",
  "te": "Telugu",
  "th": "Thai",
  "bo": "Tibetan",
  "ti": "Tigrinya",
  "to": "Tonga (Tonga Islands)",
  "ts": "Tsonga",
  "tn": "Tswana",
  "tr": "Turkish",
  "tk": "Turkmen",
  "tw": "Twi",
  "ug": "Uighur",
  "uk": "Ukrainian",
  "ur": "Urdu",
  "uz": "Uzbek",
  "ve": "Venda",
  "vi": "Vietnamese",
  "vo": "Volapük",
  "wa": "Walloon",
  "cy": "Welsh",
  "wo": "Wolof",
  "xh": "Xhosa",
  "ii": "Sichuan Yi",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "za": "Zhuang",
  "zu": "Zulu"
}
